from django.urls import path,include
from .views import (LoginOTPView,
                    VerifyOTPView,
                    LogOutAPIView,
                    ChangePasswordView,
                    UserDetailView,
                    CustomerRegisterView,
                    SellerRegisterView,
                    customer_dashboard,
                    seller_dashboard,
                    ResendOTPView,
                    PhoneLoginView,
                    PhoneVerifyOTPView)
urlpatterns = [
    path('register/customer/', CustomerRegisterView.as_view(), name='customer_register'),
    path('register/seller/', SellerRegisterView.as_view(), name='seller_register'),
    path('login/email/', LoginOTPView.as_view(), name='email_login'),
    path('login/otp-resend/', ResendOTPView.as_view(), name='otp_resend'),
    path('login/email/verify/', VerifyOTPView.as_view(), name='email_verify_otp'),
    path('login/phone/', PhoneLoginView.as_view(), name='phone_login'),
    path('login/phone/verify/', PhoneVerifyOTPView.as_view(), name='phone_verify_otp'),
    path('logout/', LogOutAPIView.as_view(), name='logout'),
    path('profile/', UserDetailView.as_view(), name='user_profile'),
    path('profile/change_password/', ChangePasswordView.as_view(), name='change_password'),
]
